// P = Prosimians ( Lemur, Loris, Tarsiers )
// M = Monkeys
// A = Apes
var species = [
  {name: 'Cheirogaleus', type: 'P', neocortexratio: 0.8, groupsize: 1},
  {name: 'Microcebus', type: 'P', neocortexratio: 0.79, groupsize: 1},
  {name: 'Lepilemur', type: 'P', neocortexratio: 0.84, groupsize: 1},
  {name: 'Lemur', type: 'P', neocortexratio: 1.23, groupsize: 9.5},
  {name: 'Avahi', type: 'P', neocortexratio: 0.96, groupsize: 2},
  {name: 'Propithecus', type: 'P', neocortexratio: 1.1, groupsize: 5},
  {name: 'Indri', type: 'P', neocortexratio: 1.24, groupsize: 4.3},
  {name: 'Daubentonia', type: 'P', neocortexratio: 1.08, groupsize: 1},
  {name: 'Loris', type: 'P', neocortexratio: 1.28, groupsize: 1},
  {name: 'Nycticebus', type: 'P', neocortexratio: 1.11, groupsize: 1},
  {name: 'Perodictus', type: 'P', neocortexratio: 1.02, groupsize: 1},
  {name: 'Galago', type: 'P', neocortexratio: 0.94, groupsize: 1},
  {name: 'Tarsier', type: 'P', neocortexratio: 1.09, groupsize: 1},
  {name: 'Callithrix', type: 'M', neocortexratio: 1.52, groupsize: 8.5},
  {name: 'Cebuella', type: 'M', neocortexratio: 1.43, groupsize: 6},
  {name: 'Saguinus', type: 'M', neocortexratio: 1.62, groupsize: 5.2},
  {name: 'Callimico', type: 'M', neocortexratio: 1.61, groupsize: 7.3},
  {name: 'Aotus', type: 'M', neocortexratio: 1.59, groupsize: 3.8},
  {name: 'Callicebus', type: 'M', neocortexratio: 1.65, groupsize: 3.3},
  {name: 'Pithecia', type: 'M', neocortexratio: 1.78, groupsize: 3.6},
  {name: 'Alouatta', type: 'M', neocortexratio: 1.82, groupsize: 8.2},
  {name: 'Ateles ', type: 'M', neocortexratio: 2.35, groupsize: 17},
  {name: 'Lagothrix', type: 'M', neocortexratio: 2.22, groupsize: 23.4},
  {name: 'Cebus', type: 'M', neocortexratio: 2.36, groupsize: 18.1},
  {name: 'Saimiri', type: 'M', neocortexratio: 2.21, groupsize: 32.5},
  {name: 'Macaca', type: 'M', neocortexratio: 2.6, groupsize: 39.6},
  {name: 'Cercocebus', type: 'M', neocortexratio: 2.38, groupsize: 15.4},
  {name: 'Papio', type: 'M', neocortexratio: 2.76, groupsize: 51.2},
  {name: 'Cercopithecus', type: 'M', neocortexratio: 2.44, groupsize: 23.9},
  {name: 'Miopithecus', type: 'M', neocortexratio: 2.33, groupsize: 65.5},
  {name: 'Erythrocebus', type: 'M', neocortexratio: 2.96, groupsize: 28.1},
  {name: 'Pygathrix', type: 'M', neocortexratio: 2.05, groupsize: null},
  {name: 'Nasalis', type: 'M', neocortexratio: 1.75, groupsize: 14.4},
  {name: 'Procolobus', type: 'M', neocortexratio: 2.22, groupsize: 35},
  {name: 'Hylobates', type: 'A', neocortexratio: 2.08, groupsize: 3.4},
  {name: 'Gorilla', type: 'A', neocortexratio: 2.65, groupsize: 7},
  {name: 'Pan', type: 'A', neocortexratio: 3.22, groupsize: 53.5},
  {name: 'Homo', type: 'H', neocortexratio: 4.1, groupsize: 150}
]
